name: Build and Update Build Folder

on:
  push:
    branches:
      - main
    # Optional: ignore changes only in the build folder to prevent infinite loops
    paths-ignore:
      - build/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run build command
        run: npm run build

      # Use an action to automatically commit any changes in the build folder
      - name: Auto commit build folder
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-update build folder after merge [skip ci]"
          # Optionally, restrict the commit to only the build folder:
          file_pattern: build/**
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
